### PR TITLE
Bump dependencies

### LINKED ISSUE #30: Recommended changes resulting from automated audit
We performed an automated audit of your Cake addin and found that it does not follow all the best practices.

We encourage you to make the following modifications:

- [x] You are currently referencing Cake.Core 0.28.1. Please upgrade to 0.33.0
- [x] The nuget package for your addin should use the cake-contrib icon. Specifically, your addin's `.csproj` should have a line like this: `<PackageIconUrl>https://cdn.jsdelivr.net/gh/cake-contrib/graphics/png/cake-contrib-medium.png</PackageIconUrl>`.

Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.

This issue was created by a tool: Cake.AddinDiscoverer version 3.12.1

### LINKED ISSUE #31: Bump dependencies to reduce Cake warnings

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #30 & #31

### CODE REVIEW

**Comment by daghb** [comment]
@phillipsj - any chance of this getting through soon?

**Comment by phillipsj** [comment]
I have stepped back from this project for a while and I thought there were
some commitments to maintain. I will incorporate any changes and do the
upgrades and get a version released this weekend.

**Comment by phillipsj** [comment]
@dag I have published version 0.17.0 with the upgrade to Cake 0.33.0.
https://www.nuget.org/packages/Cake.XdtTransform/

**Comment by daghb** [comment]
That's really cool - thank you @phillipsj !

**Pull request merged**
