### PR TITLE
Upgrade to Cake v0.22.0

### PR DESCRIPTION
**Pull request by mabreuortega**

### CODE REVIEW

**Comment by phillipsj** [comment]
Thank you for your pull request.  I will review tomorrow and get this merged in.

**Comment by Ninglin** [comment]
Any update on this? Currently having the same issue.

**Comment by phillipsj** [comment]
I have made the changes.  This PR was master branch and it would greatly help the next time to make it off of develop.

**Comment by mabreuortega** [comment]
Will do, thanks!

**Pull request closed without merging**
